---
abstract: 'CSS Selector to XPath compiler'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Test::Base: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-Selector-XPath
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter: '0'
  strict: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Corion/HTML-Selector-XPath.git
version: '0.23'
x_static_install: 1
